"""Typed registry metadata for metric pages and gradual config migration."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Final


@dataclass(frozen=True)
class SeriesSpec:
    """Describes a single series/column within a metric."""

    id: str
    label: str
    column: str
    unit: str
    threshold: float | None = None
    threshold_label: str | None = None
    threshold_direction: str = "gte"
    decimals: int = 1


@dataclass(frozen=True)
class MetricSpec:
    """Describes a metric page and the dataset it reads from."""

    id: str
    title: str
    icon: str
    summary: str
    description: str
    page_path: str
    dataset_key: str
    csv_file: str
    csv_encoding: str
    default_school: str
    nav_order: int
    threshold_note: str
    supports_branch_toggle: bool = False
    implemented: bool = True
    home_visible: bool = True
    series: tuple[SeriesSpec, ...] = ()


APP_METADATA: Final = {
    "title": "서울 소재 사립대학교 교육여건 지표 시각화",
    "subtitle": "대학알리미 공시자료 기반 대학기관평가인증 정량지표 추이 분석",
    "icon": "🎓",
    "data_updated": "2026-03-09",
    "source_name": "대학알리미",
    "source_url": "https://www.academyinfo.go.kr",
    "catalog_heading": "지표 카탈로그",
    "catalog_intro": "관심 있는 지표를 선택해 연도별 추이와 학교별 비교를 확인하세요.",
}


METRIC_REGISTRY: Final[dict[str, MetricSpec]] = {
    "budam": MetricSpec(
        id="budam",
        title="법정부담금 부담율",
        icon="🏛️",
        summary="학교법인이 법정부담금 기준 대비 실제로 부담한 비율",
        description="학교법인의 법정부담금 부담 수준을 연도별로 비교합니다.",
        page_path="pages/1_법정부담금_부담율.py",
        dataset_key="budam",
        csv_file="법정부담금_부담율.csv",
        csv_encoding="utf-8-sig",
        default_school="성신여자대학교",
        nav_order=4,
        threshold_note="4주기 인증 기준: 10% 이상",
        series=(
            SeriesSpec(
                id="budam_rate",
                label="부담율",
                column="부담율",
                unit="%",
                threshold=10.0,
                threshold_label="4주기 인증 기준",
                decimals=1,
            ),
        ),
    ),
    "gyowon": MetricSpec(
        id="gyowon",
        title="전임교원 확보율",
        icon="👩‍🏫",
        summary="법정 기준 교원 대비 실제 전임교원 확보 비율",
        description="학생정원 기준과 재학생 기준 전임교원 확보율을 비교합니다.",
        page_path="pages/2_전임교원_확보율.py",
        dataset_key="gyowon",
        csv_file="전임교원_확보율.csv",
        csv_encoding="utf-8-sig",
        default_school="성신여자대학교",
        nav_order=9,
        threshold_note="4주기 인증 기준: 61% 이상 (학생정원 기준)",
        supports_branch_toggle=True,
        series=(
            SeriesSpec(
                id="gyowon_jeongwon",
                label="학생정원 기준 확보율",
                column="전임교원 확보율(학생정원 기준)",
                unit="%",
                threshold=61.0,
                threshold_label="4주기 인증 기준",
                decimals=1,
            ),
            SeriesSpec(
                id="gyowon_jaehak",
                label="재학생 기준 확보율",
                column="전임교원 확보율(재학생 기준)",
                unit="%",
                decimals=1,
            ),
        ),
    ),
    "research": MetricSpec(
        id="research",
        title="전임교원 1인당 연구비",
        icon="💰",
        summary="전임교원 1인당 교내·교외 연구비 수혜 실적",
        description="교내 및 교외 연구비 수혜 규모를 함께 비교합니다.",
        page_path="pages/3_연구비_수혜실적.py",
        dataset_key="research",
        csv_file="연구비_수혜실적.csv",
        csv_encoding="utf-8-sig",
        default_school="성신여자대학교",
        nav_order=12,
        threshold_note="4주기 인증 기준: 교내 1,000천원 / 교외 10,000천원 이상",
        supports_branch_toggle=True,
        series=(
            SeriesSpec(
                id="research_in",
                label="교내 연구비",
                column="전임교원 1인당 연구비(교내)",
                unit="천원",
                threshold=1_000.0,
                threshold_label="4주기 인증 기준",
                decimals=0,
            ),
            SeriesSpec(
                id="research_out",
                label="교외 연구비",
                column="전임교원 1인당 연구비(교외)",
                unit="천원",
                threshold=10_000.0,
                threshold_label="4주기 인증 기준",
                decimals=0,
            ),
        ),
    ),
    "paper": MetricSpec(
        id="paper",
        title="전임교원 1인당 논문실적",
        icon="📚",
        summary="국내 등재지 논문과 SCI급·SCOPUS 국제 논문 실적",
        description="전임교원 1인당 국내·국제 논문 실적을 비교합니다.",
        page_path="pages/4_논문실적.py",
        dataset_key="paper",
        csv_file="전임교원 논문실적.csv",
        csv_encoding="cp949",
        default_school="성신여자대학교",
        nav_order=13,
        threshold_note="4주기 인증 기준: 국내 0.35편 / SCI급 0.05편 이상",
        supports_branch_toggle=True,
        series=(
            SeriesSpec(
                id="paper_jaeji",
                label="국내 등재지 논문",
                column="전임교원1인당논문실적(국내, 연구재단등재지(후보포함))",
                unit="편",
                threshold=0.35,
                threshold_label="4주기 인증 기준",
                decimals=4,
            ),
            SeriesSpec(
                id="paper_sci",
                label="SCI급·SCOPUS 논문",
                column="전임교원1인당논문실적(국제, SCI급/SCOPUS학술지)",
                unit="편",
                threshold=0.05,
                threshold_label="4주기 인증 기준",
                decimals=4,
            ),
        ),
    ),
    "jirosung": MetricSpec(
        id="jirosung",
        title="졸업생 진로 성과",
        icon="🧭",
        summary="취업 및 진학을 반영한 졸업생 진로 성과 비율",
        description="취업·진학 성과를 연도별로 비교합니다.",
        page_path="pages/5_졸업생_진로_성과.py",
        dataset_key="jirosung",
        csv_file="졸업생_취업률.csv",
        csv_encoding="utf-8-sig",
        default_school="성신여자대학교",
        nav_order=8,
        threshold_note="4주기 인증 기준: 55% 이상",
        supports_branch_toggle=True,
        series=(
            SeriesSpec(
                id="jirosung_outcome",
                label="진로 성과",
                column="졸업생_진로_성과",
                unit="%",
                threshold=55.0,
                threshold_label="4주기 인증 기준",
                decimals=1,
            ),
        ),
    ),
    "tuition": MetricSpec(
        id="tuition",
        title="세입 중 등록금 비율",
        icon="💳",
        summary="운영수입 대비 등록금수입 비율",
        description="운영수입 대비 등록금수입 비중을 연도별로 확인합니다.",
        page_path="pages/6_세입_중_등록금_비율.py",
        dataset_key="gyeolsan",
        csv_file="결산(22,23,24).csv",
        csv_encoding="utf-8-sig",
        default_school="성신여자대학교",
        nav_order=1,
        threshold_note="4주기 인증 기준: 72% 이하",
        series=(
            SeriesSpec(
                id="tuition_ratio",
                label="등록금 비율",
                column="등록금비율",
                unit="%",
                threshold=72.0,
                threshold_label="4주기 인증 기준",
                threshold_direction="lte",
                decimals=2,
            ),
        ),
    ),
    "donation": MetricSpec(
        id="donation",
        title="세입 중 기부금 비율",
        icon="🎁",
        summary="운영수입 대비 기부금수입 비율",
        description="운영수입 대비 기부금수입 비중을 연도별로 확인합니다.",
        page_path="pages/7_세입_중_기부금_비율.py",
        dataset_key="gyeolsan",
        csv_file="결산(22,23,24).csv",
        csv_encoding="utf-8-sig",
        default_school="성신여자대학교",
        nav_order=2,
        threshold_note="4주기 인증 기준: 0.4% 이상",
        series=(
            SeriesSpec(
                id="donation_ratio",
                label="기부금 비율",
                column="기부금비율",
                unit="%",
                threshold=0.4,
                threshold_label="4주기 인증 기준",
                decimals=2,
            ),
        ),
    ),
    "education_return": MetricSpec(
        id="education_return",
        title="교육비 환원율",
        icon="🎓",
        summary="등록금 수입 대비 실제 교육비 집행 수준을 보여주는 지표",
        description="교육비 환원율의 연도별 추이와 학교별 비교를 제공합니다.",
        page_path="pages/8_교육비_환원율.py",
        dataset_key="education_return",
        csv_file="processed/education_cost_return_rate/education_cost_return_rate_2020_2025_v2_schema_utf8.csv",
        csv_encoding="utf-8-sig",
        default_school="성신여자대학교",
        nav_order=6,
        threshold_note="주 표시값: 교육비 환원율(재계산)",
        series=(
            SeriesSpec(
                id="education_return_rate",
                label="교육비 환원율",
                column="교육비환원율",
                unit="%",
                threshold=110.0,
                threshold_label="기준값",
                decimals=1,
            ),
        ),
    ),
    "dormitory_rate": MetricSpec(
        id="dormitory_rate",
        title="기숙사 수용률",
        icon="🏠",
        summary="재학생 대비 기숙사 수용 가능 수준을 보여주는 지표",
        description="기숙사 수용률의 연도별 추이와 학교별 비교를 제공합니다.",
        page_path="pages/9_기숙사_수용률.py",
        dataset_key="dormitory_rate",
        csv_file="processed/dormitory_accommodation_status/dormitory_accommodation_status_v2_utf8.csv",
        csv_encoding="utf-8-sig",
        default_school="성신여자대학교",
        nav_order=19,
        threshold_note="기준값: 11% 이상",
        series=(
            SeriesSpec(
                id="dormitory_accommodation_rate",
                label="기숙사 수용률",
                column="기숙사수용률",
                unit="%",
                threshold=11.0,
                threshold_label="기준값",
                decimals=1,
            ),
        ),
    ),
    "lecturer_pay": MetricSpec(
        id="lecturer_pay",
        title="강사 강의료",
        icon="💸",
        summary="강사의 시간당 지급기준 단가를 학교별로 비교하는 지표",
        description="강사 강의료의 연도별 추이와 학교별 비교를 제공합니다.",
        page_path="pages/10_강사_강의료.py",
        dataset_key="lecturer_pay",
        csv_file="processed/lecturer_pay/lecturer_pay_2023_2025_v2_1_utf8.csv",
        csv_encoding="utf-8-sig",
        default_school="성신여자대학교",
        nav_order=11,
        threshold_note="연도별 기준값: 2023년 50,600원 / 2024년 51,800원 / 2025년 53,100원",
        series=(
            SeriesSpec(
                id="lecturer_hourly_pay",
                label="강사 강의료",
                column="강사강의료",
                unit="원",
                threshold=53_100.0,
                threshold_label="연도별 기준값",
                decimals=0,
            ),
        ),
    ),
    "library_material_purchase": MetricSpec(
        id="library_material_purchase",
        title="재학생 1인당 연간 자료구입비(결산)",
        icon="📖",
        summary="재학생 1인당 연간 자료구입비 결산 규모를 보여주는 지표",
        description="재학생 1인당 연간 자료구입비(결산)의 연도별 추이와 학교별 비교를 제공합니다.",
        page_path="pages/11_재학생_1인당_연간_자료구입비_결산.py",
        dataset_key="library_material_purchase_per_student",
        csv_file="processed/library_material_purchase_per_student/library_material_purchase_per_student_2008_2025_v2_utf8.csv",
        csv_encoding="utf-8-sig",
        default_school="성신여자대학교",
        nav_order=20,
        threshold_note="기준값: 54,000원 이상",
        series=(
            SeriesSpec(
                id="library_material_purchase_per_student",
                label="재학생 1인당 연간 자료구입비(결산)",
                column="재학생1인당연간자료구입비(결산)",
                unit="원",
                threshold=54_000.0,
                threshold_label="기준값",
                decimals=0,
            ),
        ),
    ),
    "library_staff": MetricSpec(
        id="library_staff",
        title="재학생 1,000명당 도서관 직원수",
        icon="👥",
        summary="재학생 1,000명당 도서관 직원 수를 보여주는 지표",
        description="재학생 1,000명당 도서관 직원수의 연도별 추이와 학교별 비교를 제공합니다.",
        page_path="pages/12_재학생_1000명당_도서관_직원수.py",
        dataset_key="library_staff_per_1000_students",
        csv_file="processed/library_staff_per_1000_students/library_staff_per_1000_students_2008_2025_v6_utf8.csv",
        csv_encoding="utf-8-sig",
        default_school="성신여자대학교",
        nav_order=21,
        threshold_note="기준값: 1.0명 이상",
        series=(
            SeriesSpec(
                id="library_staff_per_1000_students",
                label="재학생 1,000명당 도서관 직원수",
                column="재학생1000명당도서관직원수",
                unit="명",
                threshold=1.0,
                threshold_label="기준값",
                decimals=2,
            ),
        ),
    ),
    "corp_transfer_ratio": MetricSpec(
        id="corp_transfer_ratio",
        title="세입 중 법인전입금 비율",
        icon="🏢",
        summary="운영수입 대비 법인전입금수입 비율",
        description="운영수입 대비 법인전입금수입 비중을 연도별로 확인합니다.",
        page_path="pages/15_세입_중_법인전입금_비율.py",
        dataset_key="corp_transfer_ratio",
        csv_file="processed/kcue_university_indicators/kcue_university_metric_values_2015_2025_v1_utf8.csv",
        csv_encoding="utf-8-sig",
        default_school="성신여자대학교",
        nav_order=3,
        threshold_note="기준값: 0.4% 이상",
        series=(
            SeriesSpec(
                id="corp_transfer_ratio",
                label="법인전입금 비율",
                column="법인전입금비율",
                unit="%",
                threshold=0.4,
                threshold_label="기준값",
                decimals=2,
            ),
        ),
    ),
    "corp_finance_ratio": MetricSpec(
        id="corp_finance_ratio",
        title="법인(일반회계) 재정규모 대비 법인전입금 비율",
        icon="🏦",
        summary="법인 일반회계 재정규모 대비 법인전입금 비율",
        description="법인 재정규모 대비 법인전입금 비중을 연도별로 확인합니다.",
        page_path="",
        dataset_key="corp_finance_ratio",
        csv_file="",
        csv_encoding="utf-8-sig",
        default_school="성신여자대학교",
        nav_order=5,
        threshold_note="",
        implemented=False,
    ),
    "student_recruitment": MetricSpec(
        id="student_recruitment",
        title="학생 충원 성과",
        icon="🎒",
        summary="신입생 및 재학생 충원율 성과",
        description="학생 충원 성과의 연도별 추이와 학교별 비교를 제공합니다.",
        page_path="",
        dataset_key="student_recruitment",
        csv_file="",
        csv_encoding="utf-8-sig",
        default_school="성신여자대학교",
        nav_order=7,
        threshold_note="",
        implemented=False,
    ),
    "adjunct_faculty": MetricSpec(
        id="adjunct_faculty",
        title="겸임교원 확보율",
        icon="👨‍🏫",
        summary="겸임교원 확보율 파생값에 0.3 가중치와 4% 인정상한을 적용한 비율",
        description="겸임교원 확보율 최종 인정값의 연도별 추이와 학교별 비교를 제공합니다.",
        page_path="pages/16_겸임교원_확보율.py",
        dataset_key="adjunct_faculty",
        csv_file="processed/faculty_securing_rate/faculty_securing_rate_total_2015_2025_v1_utf8.csv",
        csv_encoding="utf-8-sig",
        default_school="성신여자대학교",
        nav_order=10,
        threshold_note="최대 인정값: 4%",
        implemented=True,
        series=(
            SeriesSpec(
                id="adjunct_faculty_quota_final",
                label="편제정원 기준 최종 인정값",
                column="겸임교원확보율(편제정원_최종)",
                unit="%",
                threshold=4.0,
                threshold_label="최대 인정값",
                decimals=3,
            ),
            SeriesSpec(
                id="adjunct_faculty_enrolled_final",
                label="재학생 기준 최종 인정값",
                column="겸임교원확보율(재학생_최종)",
                unit="%",
                threshold=4.0,
                threshold_label="최대 인정값",
                decimals=3,
            ),
        ),
    ),
    "fulltime_adjunct_faculty": MetricSpec(
        id="fulltime_adjunct_faculty",
        title="전임교원 및 겸임교원 확보율",
        icon="🧑‍🏫",
        summary="전임교원 확보율에 겸임교원 최종 인정값을 더한 교원 확보율",
        description="전임교원 확보율과 겸임교원 확보율 최종 인정값을 합산해 4주기 기준값과 비교합니다.",
        page_path="pages/17_전임교원_및_겸임교원_확보율.py",
        dataset_key="fulltime_adjunct_faculty",
        csv_file="processed/faculty_securing_rate/faculty_securing_rate_total_2015_2025_v1_utf8.csv",
        csv_encoding="utf-8-sig",
        default_school="성신여자대학교",
        nav_order=10,
        threshold_note="4주기 인증 기준: 64% 이상",
        implemented=True,
        series=(
            SeriesSpec(
                id="fulltime_adjunct_faculty_quota_rate",
                label="편제정원 기준 확보율",
                column="전임교원및겸임교원확보율(편제정원)",
                unit="%",
                threshold=64.0,
                threshold_label="4주기 인증 기준",
                decimals=3,
            ),
            SeriesSpec(
                id="fulltime_adjunct_faculty_enrolled_rate",
                label="재학생 기준 확보율",
                column="전임교원및겸임교원확보율(재학생)",
                unit="%",
                threshold=64.0,
                threshold_label="4주기 인증 기준",
                decimals=3,
            ),
        ),
    ),
    "faculty_securing_reference": MetricSpec(
        id="faculty_securing_reference",
        title="(참고)전임/겸임/초빙교원 확보율",
        icon="🧑‍🏫",
        summary="전임교원, 겸임포함, 초빙포함 교원확보율 누적 비교",
        description="첨단분야 학과 증원 기준 검토를 위해 전임·겸임포함·초빙포함 확보율을 함께 제공합니다.",
        page_path="pages/18_참고_전임_겸임_초빙교원_확보율.py",
        dataset_key="faculty_securing_reference",
        csv_file="processed/faculty_securing_rate/faculty_securing_rate_total_2015_2025_v1_utf8.csv",
        csv_encoding="utf-8-sig",
        default_school="성신여자대학교",
        nav_order=10,
        threshold_note="첨단분야 증원 참고 기준: 교원확보율 100% 이상",
        implemented=True,
        series=(
            SeriesSpec(
                id="faculty_reference_fulltime_quota_rate",
                label="전임교원(편제정원)",
                column="교원확보율(전임교원)(편제정원)",
                unit="%",
                threshold=100.0,
                threshold_label="교원확보율 100%",
                decimals=3,
            ),
            SeriesSpec(
                id="faculty_reference_fulltime_enrolled_rate",
                label="전임교원(재학생)",
                column="교원확보율(전임교원)(재학생)",
                unit="%",
                threshold=100.0,
                threshold_label="교원확보율 100%",
                decimals=3,
            ),
            SeriesSpec(
                id="faculty_reference_adjunct_included_quota_rate",
                label="겸임포함(편제정원)",
                column="교원확보율(겸임포함)(편제정원)",
                unit="%",
                threshold=100.0,
                threshold_label="교원확보율 100%",
                decimals=3,
            ),
            SeriesSpec(
                id="faculty_reference_adjunct_included_enrolled_rate",
                label="겸임포함(재학생)",
                column="교원확보율(겸임포함)(재학생)",
                unit="%",
                threshold=100.0,
                threshold_label="교원확보율 100%",
                decimals=3,
            ),
            SeriesSpec(
                id="faculty_reference_invited_included_quota_rate",
                label="초빙포함(편제정원)",
                column="교원확보율(초빙포함)(편제정원)",
                unit="%",
                threshold=100.0,
                threshold_label="교원확보율 100%",
                decimals=3,
            ),
            SeriesSpec(
                id="faculty_reference_invited_included_enrolled_rate",
                label="초빙포함(재학생)",
                column="교원확보율(초빙포함)(재학생)",
                unit="%",
                threshold=100.0,
                threshold_label="교원확보율 100%",
                decimals=3,
            ),
        ),
    ),
    "staff_per_student": MetricSpec(
        id="staff_per_student",
        title="직원 1인당 학생수",
        icon="🧑‍💼",
        summary="직원 1인당 담당 학생 수",
        description="직원 1인당 학생수의 연도별 추이와 학교별 비교를 제공합니다.",
        page_path="pages/13_직원_1인당_학생수.py",
        dataset_key="staff_per_student",
        csv_file="processed/kcue_university_indicators/kcue_university_metric_values_2015_2025_v1_utf8.csv",
        csv_encoding="utf-8-sig",
        default_school="성신여자대학교",
        nav_order=14,
        threshold_note="기준값: 70명 이하",
        series=(
            SeriesSpec(
                id="students_per_staff",
                label="직원 1인당 학생수",
                column="직원1인당학생수",
                unit="명",
                threshold=70.0,
                threshold_label="기준값",
                threshold_direction="lte",
                decimals=1,
            ),
        ),
    ),
    "scholarship_ratio": MetricSpec(
        id="scholarship_ratio",
        title="장학금 비율",
        icon="🎖️",
        summary="등록금 수입 대비 장학금 지급 비율",
        description="장학금 비율의 연도별 추이와 학교별 비교를 제공합니다.",
        page_path="pages/14_장학금_비율.py",
        dataset_key="scholarship_ratio",
        csv_file="processed/kcue_university_indicators/kcue_university_metric_values_2015_2025_v1_utf8.csv",
        csv_encoding="utf-8-sig",
        default_school="성신여자대학교",
        nav_order=15,
        threshold_note="기준값: 12% 이상",
        series=(
            SeriesSpec(
                id="scholarship_ratio",
                label="장학금 비율",
                column="장학금비율",
                unit="%",
                threshold=12.0,
                threshold_label="기준값",
                decimals=2,
            ),
        ),
    ),
    "classroom_area": MetricSpec(
        id="classroom_area",
        title="재학생 1인당 강의실 면적",
        icon="🏫",
        summary="재학생 1인당 강의실 면적 규모",
        description="재학생 1인당 강의실 면적의 연도별 추이와 학교별 비교를 제공합니다.",
        page_path="",
        dataset_key="classroom_area",
        csv_file="",
        csv_encoding="utf-8-sig",
        default_school="성신여자대학교",
        nav_order=16,
        threshold_note="",
        implemented=False,
    ),
    "lab_area": MetricSpec(
        id="lab_area",
        title="재학생 1인당 실험실습실 면적",
        icon="🔬",
        summary="재학생 1인당 실험실습실 면적 규모",
        description="재학생 1인당 실험실습실 면적의 연도별 추이와 학교별 비교를 제공합니다.",
        page_path="",
        dataset_key="lab_area",
        csv_file="",
        csv_encoding="utf-8-sig",
        default_school="성신여자대학교",
        nav_order=17,
        threshold_note="",
        implemented=False,
    ),
    "lab_equipment": MetricSpec(
        id="lab_equipment",
        title="재학생 1인당 실험실습 기자재 구입비",
        icon="🧪",
        summary="재학생 1인당 실험실습 기자재 구입비 규모",
        description="재학생 1인당 실험실습 기자재 구입비의 연도별 추이와 학교별 비교를 제공합니다.",
        page_path="",
        dataset_key="lab_equipment",
        csv_file="",
        csv_encoding="utf-8-sig",
        default_school="성신여자대학교",
        nav_order=18,
        threshold_note="",
        implemented=False,
    ),
}


SERIES_REGISTRY: Final[dict[str, SeriesSpec]] = {
    series.id: series
    for metric in METRIC_REGISTRY.values()
    for series in metric.series
}


def get_metric(metric_id: str) -> MetricSpec:
    return METRIC_REGISTRY[metric_id]


def get_series(series_id: str) -> SeriesSpec:
    return SERIES_REGISTRY[series_id]


def list_metrics() -> list[MetricSpec]:
    return sorted(METRIC_REGISTRY.values(), key=lambda item: item.nav_order)
