"""Public UI renderer exports for Streamlit pages."""

from utils.ui import (
    KPIItem,
    MetricSpec,
    OptionSection,
    SidebarConfig,
    SidebarMeta,
    SidebarRadio,
    SidebarToggle,
    ThresholdSpec,
    build_dual_metric_kpis,
    build_pivot_table,
    build_single_metric_kpis,
    build_yearly_stats,
    render_dual_metric_page,
    render_definition_table,
    render_kpis,
    render_optional_page,
    render_pivot_table,
    render_school_sidebar,
    render_single_metric_page,
    render_stats_table,
)

__all__ = [
    "KPIItem",
    "MetricSpec",
    "OptionSection",
    "SidebarConfig",
    "SidebarMeta",
    "SidebarRadio",
    "SidebarToggle",
    "ThresholdSpec",
    "build_dual_metric_kpis",
    "build_pivot_table",
    "build_single_metric_kpis",
    "build_yearly_stats",
    "render_dual_metric_page",
    "render_definition_table",
    "render_kpis",
    "render_optional_page",
    "render_pivot_table",
    "render_school_sidebar",
    "render_single_metric_page",
    "render_stats_table",
]
